id: cytof_benchmmark_exercise
description: Benchmark of different clustering algorithms for benchmark phd course.
version: 0.1
benchmarker: "Andrea Sonnenholzner, Frederik Kirk, Helene Wegener, Javier Herranz"
storage: http://omnibenchmark.org:9000
benchmark_yaml_spec: 0.04
storage_api: S3
storage_bucket_name: clusteringexampleconda
software_backend: conda
software_environments:
  py:
    description: "clustbench on py3.12.6"
    conda: envs/py.yml
    envmodule: py
  cran:
    description: "CRAN's FCPS"
    conda: envs/fcps.yml
    envmodule: fcps
metric_collectors:
  - id: plotting
    name: "Single-backend metric collector."
    software_environment: "fcps"
    repository:
      url: https://github.com/imallona/clustering_report
      commit: bbb9d56
    inputs:
      - metrics.scores
    outputs:
      - id: plotting.html
        path: "{input}/{name}/plotting_report.html"
stages:
  ## clustbench data ##########################################################

  - id: data
    modules:
      - id: data_import
        name: "CyTOF dataset from this place http://flowrepository.org/experiments/817/download_ziped_files"
        software_environment: "py"
        repository:
          url: https://github.com/kaae-2/ob-flow-datasets
          commit: 6a34a95
        parameters:
          - values: ["--dataset_name", "Levine_13dim", "--transformed", "false"]
          # - values: ["--dataset_name", "Levine_13dim", "--transformed", "true"]
          # - values: ["--dataset_name", "Levine_32dim", "--transformed", "false"]
          # - values: ["--dataset_name", "Levine_32dim", "--transformed", "true"]
          # - values: ["--dataset_name", "Mossman_rare", "--transformed", "false"]
          # - values: ["--dataset_name", "Mossman_rare", "--transformed", "true"]
          # - values: ["--dataset_name", "Nilsson_rare", "--transformed", "false"]
          # - values: ["--dataset_name", "Nilsson_rare", "--transformed", "true"]
          # - values: ["--dataset_name", "Samusik_01", "--transformed", "false"]
          # - values: ["--dataset_name", "Samusik_01", "--transformed", "true"]
          # - values: ["--dataset_name", "", "--transformed", "false"] #Template
    outputs:
      - id: data.raw
        path: "{input}/{stage}/{module}/{params}/{dataset}.data.gz"
      - id: data.labels
        path: "{input}/{stage}/{module}/{params}/{dataset}.labels.gz"
  - id: preprocessing
    modules:
      - id: data_preprocessing
        name: "Data preprocessing for CyTOF datasets"
        software_environment: "py"
        repository:
          url: https://github.com/kaae-2/ob-pipeline-preprocessing
          commit: 898733a
        parameters:

    inputs:
      - entries:
          - data.raw
          - data.labels
    outputs:
      - id: data.matrix
        path: "{input}/{stage}/{module}/{params}/{dataset}.matrix.gz"
      - id: data.true_labels
        path: "{input}/{stage}/{module}/{params}/{dataset}.true_labels.gz"

  - id: analysis
    modules:
      - id: dgcytof
        name: "DG-CyTOF"
        software_environment: "py"
        repository:
          url: #TODO: Add DG-CyTOF repo
          commit: #TODO: Add commit
        parameters:
          # - values: [] #TODO: Add parameters

      - entries:
          - data.matrix
          - data.true_labels
    outputs:
      - id: analysis.predicted_ks_range
        path: "{input}/{stage}/{module}/{params}/{dataset}_ks_range.labels.gz"
 - id: metrics
    modules:
      - id: flow_metrics
        name: "benchmark metrics for flow/cytof data"
        software_environment: "py"
        repository:
          url:
          commit:
        parameters:
       #  - values: [] #TODO: Add parameters
    inputs:
      - entries:
          - analysis.predicted_ks_range
          - data.true_labels
    outputs:
      - id: metrics.scores
        path: "{input}/{stage}/{module}/{params}/{dataset}.scores.gz"

#   - id: metrics
#     modules:
#       - id: partition_metrics
#         name: "clustbench partition metrics"
#         software_environment: "clustbench"
#         repository:
#           url: https://github.com/imallona/clustbench_metrics
#           commit: 9132d45
#         parameters:
#           - values: ["--metric", "normalized_clustering_accuracy"]
#           - values: ["--metric", "adjusted_fm_score"]
#           # - values: ["--metric", "adjusted_mi_score"]
#           # - values: ["--metric", "adjusted_rand_score"]
#           # - values: ["--metric", "fm_score"]
#           # - values: ["--metric", "mi_score"]
#           # - values: ["--metric", "normalized_clustering_accuracy"]
#           # - values: ["--metric", "normalized_mi_score"]
#           # - values: ["--metric", "normalized_pivoted_accuracy"]
#           # - values: ["--metric", "pair_sets_index"]
#           # - values: ["--metric", "rand_score"]
#     inputs:
#       - entries:
#           - clustering.predicted_ks_range
#           - data.true_labels
#     outputs:
#       - id: metrics.scores
#         path: "{input}/{stage}/{module}/{params}/{dataset}.scores.gz"
