id: cytof_benchmmark_exercise
description: Benchmark of different clustering algorithms for benchmark phd course.
version: 0.1
benchmarker: "Andrea Sonnenholzner, Frederik Kirk, Helene Wegener, Javier Herranz"
storage: http://omnibenchmark.org:9000
benchmark_yaml_spec: 0.04
storage_api: S3
storage_bucket_name: clusteringexampleconda
software_backend: conda
software_environments:
  bash:
    description: "bash"
    conda: envs/bash.yml
    envmodule: bash
  # py:
  #   description: "clustbench on py3.12.6"
  #   conda: envs/py.yml
  #   envmodule: py
  # py-old:
  #   description: "clustbench on py3.12.6"
  #   conda: envs/py-old.yml
  #   envmodule: py-old
  cran:
    description: "CRAN R environment"
    conda: envs/cran.yml
    envmodule: cran
  # cyanno:
  #   description: "CyAnno module environment"
  #   conda: envs/cyanno_env.yml
  #   envmodule: cyanno

# metric_collectors:
#   - id: plotting
#     name: "Single-backend metric collector."
#     software_environment: "cran"
#     repository:
#       url: https://github.com/imallona/clustering_report
#       commit: bbb9d56
#     inputs:
#       - metrics.scores
#     outputs:
#       - id: plotting.html
#         path: "{input}/{name}/plotting_report.html"
stages:
  ## clustbench data ##########################################################


  - id: preprocessing

    modules:
      - id: data_preprocessing
        software_environment: "bash"
        repository:
          url: https://github.com/helenewegener1/ob-pipeline-preprocessing
          commit: 8a0e3d3a0eaa3d4dfc285bd82c3d11d213433589

        # Cross-validation seed
        parameters:
          - values: ["--data_set", /home/projects/dp_immunoth/data/benchmark_flow/FR-FCM-Z2KP_healthy_final, "--seed", 1]
    
    # inputs:
    #   - id: data_path
    #     type: folder
    #     value: "/home/projects/dp_immunoth/data/benchmark_flow/FR-FCM-Z2KP_healthy_final"

    # Outputs (same names, Omnibenchmark will handle separate runs)
    outputs:
      - id: train.data.matrix
        path: "{input}/{stage}/{module}/{params}/{dataset}/train_x.zip"
      - id: labels_train
        path: "{input}/{stage}/{module}/{params}/{dataset}/train_y.zip"
      - id: test.data.matrix
        path: "{input}/{stage}/{module}/{params}/{dataset}/test_x.zip"
      - id: labels_test
        path: "{input}/{stage}/{module}/{params}/{dataset}/test_y.zip"


  - id: analysis
    inputs:
      - entries:
          - test.data.matrix
          - labels_test
          - train.data.matrix
          - labels_train
    
    modules:
    
      - id: lda
        name: "LDA"
        software_environment: cran
        repository:
          url: https://github.com/helenewegener1/ob-pipeline-LDA
          commit: 7d17b7e8f1d864ddd9ede88cb1c5853a3c3f7aed
        parameters: []

      # - id: dgcytof
      #   name: "DG-CyTOF"
      #   software_environment: py
      #   repository:
      #     url: https://github.com/helenewegener1/ob-pipeline-dgcytof
      #     commit: f28d69b75e9b85f6138ca2646293d3ec10d5a9f9
      #   parameters: []
      # 
      # - id: cyanno
      #   name: "CyAnno annotator"
      #   software_environment: cyanno
      #   repository:
      #     url: https://github.com/helenewegener1/ob-pipeline-cyanno
      #     commit: dc467999596c8a0f35250980cae76dc8c1f9807e
      #   parameters: []

      #- id: gatemeclass
        #name: "GateMeClass statistical annotation"
        #software_environment: cran
        #repository:
          #url: https://github.com/andreasonnen/gatemeclass
          #commit: 269bc21964d95479f8301f76baddbc3346310465
        #parameters:
          #- values: ["--GMM_parameterization", "V", "--sampling", "0.1", "--k", "20", "--seed", "42"]
          # - values: ["--GMM_parameterization", "E", "--sampling", "0.2", "--k", "30", "--seed", "42"]

      # - id: random
      #   name: "Random"
      #   software_environment: cran
      #   repository:
      #     url: https://github.com/helenewegener1/benchmark_random
      #     commit: 8656434404c3b7818262c6074b1602a8bd60c90d
      #   parameters: []

    outputs:
      - id: analysis.prediction
        path: "{input}/{stage}/{module}/{params}/{dataset}_predicted_labels.txt"
  # 
  # - id: metrics
  #   modules:
  #     - id: flow_metrics
  #       name: "benchmark metrics for flow/cytof data"
  #       software_environment: "py"
  #       repository:
  #         url: https://github.com/helenewegener1/ob-pipeline-metrics
  #         commit: b57eeb13fb15757e4e4730ce90351c5d329c5ad4
  #       parameters:
  #         - values: ["--metric", "all"]
  #       #  - values: ["--metric", "accuracy"]
  #       #  - values: ["--metric", "precision"]
  #       #  - values: ["--metric", "recall"]
  #       #  - values: ["--metric", "f1"]
  #       #  - values: ["--metric", "f1_score"]
  #       #  - values: ["--metric", "runtime"]
  #       #  - values: ["--metric", "overlap"]
  #       #  - values: ["--metric", "scalability"]
  #     #  - values: ["--metric", ""] #Template: Add parameters
  #   inputs:
  #     - entries:
  #         - analysis.prediction
  #         - labels_test
  #   outputs:
  #     - id: metrics.scores
  #       path: "{input}/{stage}/{module}/{params}/{dataset}.flow_metrics.json.gz"
